# Generated by Django 4.2.7 on 2023-11-19 18:32

import MaasApp.models.location
import MaasApp.models.vehicle
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('MaasApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150, null=True)),
                ('capacity', models.IntegerField(null=True)),
                ('type', django_enumfield.db.fields.EnumField(enum=MaasApp.models.location.LocationType, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', django_enumfield.db.fields.EnumField(enum=MaasApp.models.vehicle.VehicleType)),
                ('model', models.CharField(max_length=100, null=True)),
                ('license_plate', models.CharField(max_length=6)),
                ('status', django_enumfield.db.fields.EnumField(enum=MaasApp.models.vehicle.Status, null=True)),
                ('info', models.TextField(null=True)),
                ('condition', django_enumfield.db.fields.EnumField(enum=MaasApp.models.vehicle.Condition, null=True)),
                ('charging_level', models.IntegerField(null=True)),
                ('capacity', models.IntegerField(null=True)),
                ('date_of_purchase', models.DateField(null=True)),
                ('insurance_info', models.TextField(null=True)),
                ('maintenance_history', models.TextField(null=True)),
                ('current_location_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MaasApp.location')),
            ],
        ),
    ]
