# Generated by Django 4.2.7 on 2023-11-19 19:06

import MaasApp.models.payment
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('MaasApp', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=django_enumfield.db.fields.EnumField(default=0, enum=MaasApp.models.payment.PaymentStatus),
        ),
    ]
