# Generated by Django 4.2.7 on 2023-11-19 19:17

import MaasApp.models.booking
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('MaasApp', '0004_alter_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('status', django_enumfield.db.fields.EnumField(default=0, enum=MaasApp.models.booking.BookingStatus)),
                ('username', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='MaasApp.user')),
                ('vehicle_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='MaasApp.vehicle')),
            ],
        ),
    ]
