# Generated by Django 4.2.7 on 2023-11-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaasApp', '0005_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_dev',
        ),
        migrations.RemoveField(
            model_name='user',
            name='joined_date',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
