# Generated by Django 4.2.7 on 2023-12-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaasApp', '0007_rename_current_location_id_vehicle_current_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnqueteResponse',
            fields=[
                ('respondent_id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('completion_time', models.DateTimeField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_modified_time', models.DateTimeField(blank=True, null=True)),
                ('origin', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.CharField(blank=True, max_length=20, null=True)),
                ('travel_frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('available_transportation', models.CharField(blank=True, max_length=200, null=True)),
                ('most_used_transport_modes', models.CharField(blank=True, max_length=200, null=True)),
                ('consider_shared_mobility', models.CharField(blank=True, max_length=200, null=True)),
                ('maas_app_used', models.CharField(blank=True, max_length=3, null=True)),
                ('maas_usage_frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('maas_app_advantages', models.TextField(blank=True, null=True)),
                ('cost_overview_value_added', models.TextField(blank=True, null=True)),
                ('satisfaction_transport_modes', models.CharField(blank=True, max_length=50, null=True)),
                ('survey_comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
