# Generated by Django 4.2.8 on 2023-12-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaasApp', '0008_enqueteresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enqueteresponse',
            name='completion_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='enqueteresponse',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
