# Generated by Django 4.2.8 on 2023-12-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaasApp', '0009_alter_enqueteresponse_completion_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enqueteresponse',
            name='completion_time',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='enqueteresponse',
            name='start_time',
            field=models.CharField(max_length=18, null=True),
        ),
    ]
