# Generated by Django 4.2.8 on 2023-12-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaasApp', '0010_alter_enqueteresponse_completion_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enqueteresponse',
            name='completion_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='enqueteresponse',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
