from MaasApp.models.location import LocationType

locations_data = [
    {
        'name': 'Beverwijk Station',
        'address': 'Stationsplein 46, 1948 LC Beverwijk',
        'capacity': 100,
        'type': LocationType.TRAIN_STATION,
        'latitude': 52.487222,
        'longitude': 4.652778,
        'description': 'Main train station in Beverwijk.',
    },
    {
        'name': 'Beverwijk Centrum',
        'address': 'Breestraat 80, 1941 EK Beverwijk',
        'capacity': 50,
        'type': LocationType.BUS_STOP,
        'latitude': 52.483056,
        'longitude': 4.656111,
        'description': 'Bus stop at the city center.',
    },
    {
        'name': 'P1 Parkeergarage',
        'address': 'Begraafplaats 1, 1943 PE Beverwijk',
        'capacity': 200,
        'type': LocationType.PARKING_AREA,
        'latitude': 52.489167,
        'longitude': 4.659722,
        'description': 'Parking garage near the city center.',
    },
    {
        'name': 'Beverwijk Scooter Point',
        'address': 'Koningstraat 37, 1941 BB Beverwijk',
        'capacity': 20,
        'type': LocationType.SCOOTER_STATION,
        'latitude': 52.485833,
        'longitude': 4.658333,
        'description': 'Scooter point near the city center.',
    },
    {
        'name': 'Beverwijk Hub',
        'address': 'Parallelweg 128, 1948 NN Beverwijk',
        'capacity': 150,
        'type': LocationType.HUB,
        'latitude': 52.486944,
        'longitude': 4.653889,
        'description': 'Main mobility hub in Beverwijk.',
    },
    {
        'name': 'Beverwijk Drop-off Point',
        'address': 'Zeestraat 74, 1942 AR Beverwijk',
        'capacity': 10,
        'type': LocationType.DROP_OFF_POINT,
        'latitude': 52.491667,
        'longitude': 4.656944,
        'description': 'Drop-off point near the city center.',
    },
    {
        'name': 'Beverwijk Pick-up Point',
        'address': 'Begraafplaats 1, 1943 PE Beverwijk',
        'capacity': 10,
        'type': LocationType.PICK_UP_POINT,
        'latitude': 52.489167,
        'longitude': 4.659722,
        'description': 'Pick-up point near the city center.',
    },
    {
        'name': 'Beverwijk Transit Center',
        'address': 'Stationsplein 46, 1948 LC Beverwijk',
        'capacity': 100,
        'type': LocationType.TRANSIT_CENTER,
        'latitude': 52.487222,
        'longitude': 4.652778,
        'description': 'Transit center in Beverwijk.',
    },
    {
        'name': 'Beverwijk Random Point',
        'address': 'Breestraat 80, 1941 EK Beverwijk',
        'capacity': 0,
        'type': LocationType.RANDOM_POINT,
        'latitude': 52.483056,
        'longitude': 4.656111,
        'description': 'Random point in Beverwijk.',
    },
    {
        'name': 'Beverwijk Bike Station',
        'address': 'Stationsplein 46, 1948 LC Beverwijk',
        'capacity': 100,
        'type': LocationType.BIKE_STATION,
        'latitude': 52.487222,
        'longitude': 4.652778,
        'description': 'Bike station at Beverwijk train station.',
    },
]
