users_data = [
            {'username': 'user1', 'email': 'user1@example.com', 'password': 'password1', 'first_name': 'John',
             'last_name': 'Doe'},
            {'username': 'user2', 'email': 'user2@example.com', 'password': 'password2', 'first_name': 'Jane',
             'last_name': 'Doe'},
            {'username': 'user3', 'email': 'user3@example.com', 'password': 'password3', 'first_name': 'Bob',
             'last_name': 'Smith'},
            {'username': 'user4', 'email': 'user4@example.com', 'password': 'password4', 'first_name': 'Alice',
             'last_name': 'Johnson'},
            {'username': 'user5', 'email': 'user5@example.com', 'password': 'password5', 'first_name': 'Charlie',
             'last_name': 'Brown'},
            {'username': 'user6', 'email': 'user6@example.com', 'password': 'password6', 'first_name': 'Diana',
             'last_name': 'Ross'},
            {'username': 'user7', 'email': 'user7@example.com', 'password': 'password7', 'first_name': 'Edward',
             'last_name': 'Norton'},
            {'username': 'user8', 'email': 'user8@example.com', 'password': 'password8', 'first_name': 'Fiona',
             'last_name': 'Smith'},
            {'username': 'user9', 'email': 'user9@example.com', 'password': 'password9', 'first_name': 'George',
             'last_name': 'Harrison'},
            {'username': 'user10', 'email': 'user10@example.com', 'password': 'password10', 'first_name': 'Helen',
             'last_name': 'Jones'},
        ]