import random
from datetime import datetime, timedelta
from ..seeding_data.location_data import locations_data
from MaasApp.models.vehicle import Status, Condition, VehicleType
from MaasApp.models.location import LocationType, Location

vehicles_data = [
    {
        'type': VehicleType.CAR,
        'model': 'Tesla Model 3',
        'license_plate': 'AB-123-CD',
        'status': Status.AVAILABLE,
        'info': 'Electric car with autopilot feature.',
        'condition': Condition.GOOD,
        'charging_level': 100,
        'capacity': 5,
        'date_of_purchase': datetime.now() - timedelta(days=365),
        'insurance_info': 'Insured by XYZ Insurance.',
        'maintenance_history': 'Last maintenance on ' + str(datetime.now() - timedelta(days=60)),
    },
    {
        'type': VehicleType.BIKE,
        'model': 'VanMoof S3',
        'license_plate': 'BIKE-456',
        'status': Status.IN_USE,
        'info': 'Electric bike with automatic electronic shifting.',
        'condition': Condition.FAIR,
        'charging_level': 75,
        'capacity': 1,
        'date_of_purchase': datetime.now() - timedelta(days=180),
        'insurance_info': 'Insured by ABC Insurance.',
        'maintenance_history': 'Last maintenance on ' + str(datetime.now() - timedelta(days=30)),
    },
    {
        'type': VehicleType.BIKE,
        'model': 'Gazelle Orange C7+',
        'license_plate': 'BIKE-789',
        'status': Status.AVAILABLE,
        'info': 'Comfortable city bike with 7 gears.',
        'condition': Condition.GOOD,
        'charging_level': 100,
        'capacity': 1,
        'date_of_purchase': datetime.now() - timedelta(days=90),
        'insurance_info': 'Insured by DEF Insurance.',
        'maintenance_history': 'Last maintenance on ' + str(datetime.now() - timedelta(days=15)),
    },
    {
        'type': VehicleType.BIKE,
        'model': 'Cortina U4 Transport',
        'license_plate': 'BIKE-321',
        'status': Status.IN_MAINTENANCE,
        'info': 'Sturdy transport bike with front carrier.',
        'condition': Condition.FAIR,
        'charging_level': 85,
        'capacity': 1,
        'date_of_purchase': datetime.now() - timedelta(days=200),
        'insurance_info': 'Insured by GHI Insurance.',
        'maintenance_history': 'Last maintenance on ' + str(datetime.now() - timedelta(days=30)),
    },
    {
        'type': VehicleType.BIKE,
        'model': 'Gazelle Orange C7+',
        'license_plate': 'BIKE-789',
        'status': Status.AVAILABLE,
        'info': 'Comfortable city bike with 7 gears.',
        'condition': Condition.GOOD,
        'charging_level': 100,
        'capacity': 1,
        'date_of_purchase': datetime.now() - timedelta(days=90),
        'insurance_info': 'Insured by DEF Insurance.',
        'maintenance_history': 'Last maintenance on ' + str(datetime.now() - timedelta(days=15)),
    },
    {
        'type': VehicleType.BIKE,
        'model': 'Cortina U4 Transport',
        'license_plate': 'BIKE-321',
        'status': Status.IN_MAINTENANCE,
        'info': 'Sturdy transport bike with front carrier.',
        'condition': Condition.FAIR,
        'charging_level': 85,
        'capacity': 1,
        'date_of_purchase': datetime.now() - timedelta(days=200),
        'insurance_info': 'Insured by GHI Insurance.',
        'maintenance_history': 'Last maintenance on ' + str(datetime.now() - timedelta(days=30)),
    },
    {
        'type': VehicleType.SCOOTER,
        'model': 'Segway Ninebot',
        'license_plate': 'SCOOT-789',
        'status': Status.IN_MAINTENANCE,
        'info': 'Electric scooter with a range of up to 40 miles.',
        'condition': Condition.POOR,
        'charging_level': 20,
        'capacity': 1,
        'date_of_purchase': datetime.now() - timedelta(days=90),
        'insurance_info': 'Insured by DEF Insurance.',
        'maintenance_history': 'Last maintenance on ' + str(datetime.now() - timedelta(days=15)),
    },
    {
        'type': VehicleType.BUS,
        'model': 'Mercedes-Benz Citaro',
        'license_plate': 'BUS-012',
        'status': Status.OUT_OF_SERVICE,
        'info': 'City bus with a capacity of up to 100 passengers.',
        'condition': Condition.FAIR,
        'charging_level': None,
        'capacity': 100,
        'date_of_purchase': datetime.now() - timedelta(days=730),
        'insurance_info': 'Insured by GHI Insurance.',
        'maintenance_history': 'Last maintenance on ' + str(datetime.now() - timedelta(days=120)),
    },
    {
        'type': VehicleType.TRAIN,
        'model': 'NS Sprinter Lighttrain',
        'license_plate': 'TRAIN-345',
        'status': Status.AVAILABLE,
        'info': 'Local train with a capacity of up to 300 passengers.',
        'condition': Condition.GOOD,
        'charging_level': None,
        'capacity': 300,
        'date_of_purchase': datetime.now() - timedelta(days=1460),
        'insurance_info': 'Insured by JKL Insurance.',
        'maintenance_history': 'Last maintenance on ' + str(datetime.now() - timedelta(days=180)),
    },
    {
        'type': VehicleType.BIKE,
        'model': 'OV-fiets',
        'license_plate': 'OVF-789',
        'status': Status.AVAILABLE,
        'info': 'Public transport bike available at Beverwijk station.',
        'condition': Condition.GOOD,
        'charging_level': 100,
        'capacity': 1,
        'date_of_purchase': datetime.now() - timedelta(days=150),
        'insurance_info': 'Insured by OV-fiets Insurance.',
        'maintenance_history': 'Last maintenance on ' + str(datetime.now() - timedelta(days=25)),
    },
    {
        'type': VehicleType.BIKE,
        'model': 'OV-fiets',
        'license_plate': 'OVF-321',
        'status': Status.IN_USE,
        'info': 'Public transport bike currently in use from Beverwijk station.',
        'condition': Condition.FAIR,
        'charging_level': 70,
        'capacity': 1,
        'date_of_purchase': datetime.now() - timedelta(days=260),
        'insurance_info': 'Insured by OV-fiets Insurance.',
        'maintenance_history': 'Last maintenance on ' + str(datetime.now() - timedelta(days=65)),
    },
    {
        'type': VehicleType.BIKE,
        'model': 'OV-fiets',
        'license_plate': 'OVF-654',
        'status': Status.IN_MAINTENANCE,
        'info': 'Public transport bike currently in maintenance at Beverwijk station.',
        'condition': Condition.POOR,
        'charging_level': 50,
        'capacity': 1,
        'date_of_purchase': datetime.now() - timedelta(days=300),
        'insurance_info': 'Insured by OV-fiets Insurance.',
        'maintenance_history': 'Last maintenance on ' + str(datetime.now() - timedelta(days=70)),
    },
    {
        'type': VehicleType.BIKE,
        'model': 'OV-fiets',
        'license_plate': 'OVF-987',
        'status': Status.AVAILABLE,
        'info': 'Public transport bike available at Beverwijk station.',
        'condition': Condition.GOOD,
        'charging_level': 90,
        'capacity': 1,
        'date_of_purchase': datetime.now() - timedelta(days=180),
        'insurance_info': 'Insured by OV-fiets Insurance.',
        'maintenance_history': 'Last maintenance on ' + str(datetime.now() - timedelta(days=30)),
    },
    {
        'type': VehicleType.BIKE,
        'model': 'OV-fiets',
        'license_plate': 'OVF-246',
        'status': Status.OUT_OF_SERVICE,
        'info': 'Public transport bike currently out of service at Beverwijk station.',
        'condition': Condition.POOR,
        'charging_level': 30,
        'capacity': 1,
        'date_of_purchase': datetime.now() - timedelta(days=400),
        'insurance_info': 'Insured by OV-fiets Insurance.',
        'maintenance_history': 'Last maintenance on ' + str(datetime.now() - timedelta(days=100)),
    }
]
